goals:
  priority: ['performance', 'power', 'area']
  targets: { performance_mhz: 500 }

environment:
  eda_command: "make synthesis"
  flow_config_file: "./libre_config.mk"
  verification_command: "make -f Makefile.sim sim"

cline_integration:
  api_key: "${CLINE_API_KEY}"
  model: "claude-sonnet-4-20250514"
  auto_approve_refinement: true
  max_refinement_iterations: 5

exploration:
  parallel_candidates: 3
  max_tree_depth: 5
  expand_threshold: 50
  objective_value_threshold: 150
  loop_sleep_sec: 5

collaboration:
  help_mode: enabled
  max_open_tickets: 5
  ticket_keyword_blacklist: ["style", "naming", "syntax"]
